### ISSUE TITLE
Привести файл статті AboutSuperintelligence до markdown формату

### ISSUE THREAD

**Issue by Taras-Parfeniuk** [Taras-Parfeniuk/BSA17_Lecture1_HomeWork#1]

**Comment by volodymyr-kushnir** [comment]
...і заодно перейменувати файли в .md, інакше GitHub не буде вмикати парсер Markdown. Умова завдання не порушується, адже файли і далі будуть "текстовими".

**Comment by Taras-Parfeniuk** [comment]
Дякую
за .md знав, а от на рахунок повідомлення комміту цікаво
